### ISSUE TITLE
AC Ladeleistung steuerbar?

### ISSUE THREAD

**Issue by 0xdefec71f** [Newan/ioBroker.ecoflow#10]
Hallo zusammen,
bevor ich mir einen Ecoflow Powerstation zulege, wäre es für mich essentiell zu wissen, ob über diesen Adapter auch die AC Ladeleistung gesteuert werden kann. Über die App ist dies ja zwischen 200W und xW möglich. Kann mir das bitte jemand beantworten?
VG

**Comment by misko85** [comment]
Hallo,
über diesen Adapter ist es aktuell nicht möglich. Er liefert nur rudimentäre Daten/Informationen.

![image](https://user-images.githubusercontent.com/115806751/224124073-884616bb-2228-42e5-8cd6-8a4d0bac51a7.png)

Es gibt jedoch eine Alternativ für den ioBroker, die etwas mehr Arbeit bedeutet als einen Adapter zu installieren, dafür aber aktuell alle Funktionen bietet. Das läuft bei mir und soweit funktioniert auch alles.

Siehe hier:
https://haus-automatisierung.com/hardware/2023/02/13/ecoflow-river-2-usv-batteriespeicher.html
und hier:
https://forum.iobroker.net/topic/54929/adapter-f%C3%BCr-ecoflow-einbindung/69

**Comment by 0xdefec71f** [comment]
Ah, vielen Dank für die Links! Das schaue ich mir mal ausgiebig an. VG
