### ISSUE TITLE
secretKey no match

### ISSUE THREAD

**Issue by sunny20k17** [Newan/ioBroker.ecoflow#11]
Hallo zusammen,
seit kurzem stellt der Adapter keine Verbindung mehr zu meiner Eco Flow Delta Pro her. Bis dahin hatte der Adapter super funktioniert.
Selbst das Update von 0.2 auf 0.4 brachte keinen Erfolg. Der secretKey ist 100% richtig. Habe mir für meine River Pro ebenfalls vor kurzem die Zugangsdaten zukommen lassen, auch die lässt sich nicht abrufen.

Wenn ich ein GET absetzte erhalte ich die Daten im Browser.

**Screenshots & Logfiles**  
ecoflow.0 | 2023-03-11 08:49:06.375 | error | secretKey no match

**Versions:**  
 - Adapter version: <0.4>
 - JS-Controller version: <4.0.24> <
 - Node version: <v16.17.1> 
 - Operating system: <linux>

**Comment by DerMarioH** [comment]
Hallo,
ich habe genau das selbe Problem. 
Im ioBroker habe ich zwei Instanzen. Erst hatte ich keine Verbindung in der ersten Instanz, dann ist die Verbindung in der zweiten Instanz abgebrochen.
Ich habe den Proxmox-Container auf eine ältere Version zurück gesetzt. Leider auch kein Erfolg.
Nun habe ich einen neuen Code bei Ecoflow beantragt. Mal schauen ob es daran liegt.

**Comment by DerMarioH** [comment]
Mit neuem secretKey klappt es nun.
