### ISSUE TITLE
Please correct npm maintainers configuration.

### ISSUE THREAD

**Issue by GermanBluefox** [Newan/ioBroker.ecoflow#13]
## ioBroker adapter checker for npm access

Access right check for adapter ecoflow returned the following issue:

Bluefox was not found in the collaborators on NPM!.
Please execute in adapter directory: "npm owner add bluefox iobroker.ecoflow"

Current maintainers are 
    realnewan <info@newan.de>

Please fix the above error as soon as possible.
All adapters listed at ioBroker repositories must have 'bluefox' added as maintainer.

Future version updates at the repositories will be suspended until this problem is fixed.

**Comment by Newan** [comment]
@GermanBluefox  @mcm1957 User already has a pending invite

**Comment by mcm1957** [comment]
@newan
Please check invite. Maybe its timed-out.
At least @GermanBluefox has not yet accepted the invite

C:\Users\Martin>npm owner list iobroker.ecoflow
realnewan <info@newan.de>

**Comment by mcm1957** [comment]
@Newan
Please check invite. Maybe its timed-out.
And/or create a new one please.
At least @GermanBluefox has not yet accepted the invite
 until now.

C:\Users\Martin>npm owner list iobroker.ecoflow
realnewan [info@newan.de](mailto:info@newan.de)

**Comment by Newan** [comment]
> npm owner add bluefox iobroker.ecoflow

npm notice INFO: User bluefox invited to package iobroker.ecoflow successfully.
+ bluefox (iobroker.ecoflow)

@mcm1957 I added it multiple times

**Comment by mcm1957** [comment]
THANKS for feedback and invite.
I've jiust polled bluefox via telegram. Lets see if it worked.
