### ISSUE TITLE
Is this adapter still maintained ? - PLEASE RESPOND

### ISSUE THREAD

**Issue by mcm1957** [Newan/ioBroker.ecoflow#16]
Please let us know if this adapter ist still maintained.

There are a few open issue describing a problem and NPM Owner configuration is open since months. (https://github.com/Newan/ioBroker.ecoflow/issues/13)

Please repond with any short comment (and fix npm ownership as soon as you time allows)

**IMPORTANT:**
**If there is no response until 15.5.204 we will consider to remove the adapter from repository.**

**Comment by mcm1957** [comment]
Just a kind reminder

**If there is no response until 15.5.204 we will consider to remove the adapter from repository.**

**Comment by Newan** [comment]
yes, but the time is limited.
PR are welcome

**Comment by mcm1957** [comment]
Thanks this info is completly sufficient :-)
I only try to sort out adapters where noby even reacts anymore,

Short time is a common Problem ....
